import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { childrenAPI, memoryAPI, interactionsAPI } from '../api/client'
import { ArrowLeft, Download, Brain, Zap, Activity } from 'lucide-react'

export default function TherapistView() {
  const { childId } = useParams()
  const navigate = useNavigate()
  const [child, setChild] = useState(null)
  const [patterns, setPatterns] = useState(null)
  const [history, setHistory] = useState([])
  const [note, setNote] = useState('')
  const [saving, setSaving] = useState(false)
  const [savedMsg, setSavedMsg] = useState('')
  const [activeTab, setActiveTab] = useState('patterns')

  useEffect(() => {
    Promise.all([
      childrenAPI.get(childId),
      memoryAPI.patterns(childId),
      interactionsAPI.history(childId, 30)
    ]).then(([c, p, h]) => { setChild(c); setPatterns(p); setHistory(h) })
  }, [childId])

  async function saveNote() {
    if (!note.trim()) return
    setSaving(true)
    await childrenAPI.addNote(childId, note.trim(), 'therapist')
    setNote('')
    setSavedMsg('Note saved!')
    setTimeout(() => setSavedMsg(''), 3000)
    setSaving(false)
  }

  function exportReport() {
    const report = {
      child: child?.name,
      age: child?.age,
      exportDate: new Date().toLocaleDateString(),
      summary: {
        totalPatterns: (patterns?.gestures?.length || 0) + (patterns?.sounds?.length || 0) + (patterns?.objects?.length || 0),
        totalInteractions: history.length,
        confirmedInteractions: history.filter(h => h.caregiver_confirmed).length,
      },
      knownGestures: patterns?.gestures?.map(g => ({ gesture: g.gesture, intent: g.intent, timesConfirmed: g.count })),
      knownSounds: patterns?.sounds?.map(s => ({ sound: s.sound, intent: s.intent, timesConfirmed: s.count })),
      knownObjects: patterns?.objects?.map(o => ({ object: o.object, intent: o.intent, timesConfirmed: o.count })),
      recentCommunications: history.slice(0, 10).map(h => ({ time: h.time, intent: h.confirmed_intent || h.predicted_intent, confidence: h.confidence })),
      disclaimer: 'This report is generated by SpeakUp, an assistive communication tool. It is NOT a medical diagnosis and should be used for communication support only.'
    }
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${child?.name}_speakup_report_${new Date().toISOString().split('T')[0]}.json`
    a.click()
  }

  if (!child) return <div className="flex items-center justify-center h-64"><div className="animate-spin w-10 h-10 border-4 border-indigo-500 border-t-transparent rounded-full" /></div>

  const totalPatterns = (patterns?.gestures?.length || 0) + (patterns?.sounds?.length || 0) + (patterns?.objects?.length || 0)

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <button onClick={() => navigate('/')} className="text-gray-400 hover:text-gray-700"><ArrowLeft className="w-5 h-5" /></button>
          <div>
            <h1 className="text-xl font-bold text-gray-900">Therapist / Professional View</h1>
            <p className="text-sm text-gray-400">{child.name} — Communication Analysis</p>
          </div>
        </div>
        <button onClick={exportReport} className="flex items-center gap-2 bg-green-600 text-white px-4 py-2 rounded-xl text-sm font-medium hover:bg-green-700">
          <Download className="w-4 h-4" /> Export Report
        </button>
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6 text-amber-800 text-sm">
        ⚕️ <strong>Important:</strong> SpeakUp is an assistive communication tool — not a diagnostic or medical device. All observations are for communication support purposes only.
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        {[
          { icon: Brain, label: 'Learned Patterns', val: totalPatterns },
          { icon: Activity, label: 'Total Sessions', val: history.length },
          { icon: Zap, label: 'Confirmed', val: history.filter(h => h.caregiver_confirmed).length },
        ].map(s => (
          <div key={s.label} className="bg-white rounded-2xl p-4 shadow-sm border border-gray-100 text-center">
            <s.icon className="w-6 h-6 text-indigo-600 mx-auto mb-2" />
            <div className="text-2xl font-bold text-gray-900">{s.val}</div>
            <div className="text-xs text-gray-500">{s.label}</div>
          </div>
        ))}
      </div>

      {/* Tabs */}
      <div className="flex gap-2 mb-6">
        {['patterns', 'history', 'notes'].map(t => (
          <button key={t} onClick={() => setActiveTab(t)}
            className={`px-4 py-2 rounded-xl text-sm font-medium capitalize ${activeTab === t ? 'bg-indigo-600 text-white' : 'bg-white border border-gray-200 text-gray-600'}`}>
            {t === 'patterns' ? '🧠 Known Patterns' : t === 'history' ? '📋 Session History' : '📝 Notes'}
          </button>
        ))}
      </div>

      {activeTab === 'patterns' && patterns && (
        <div className="space-y-4">
          {[
            { title: 'Confirmed Gestures', items: patterns.gestures, keyField: 'gesture' },
            { title: 'Confirmed Sounds', items: patterns.sounds, keyField: 'sound' },
            { title: 'Confirmed Objects', items: patterns.objects, keyField: 'object' },
          ].map(section => (
            <div key={section.title} className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
              <h3 className="font-semibold text-gray-800 mb-3">{section.title} ({section.items?.length || 0})</h3>
              {section.items?.length > 0 ? (
                <div className="space-y-2">
                  {section.items.map(item => (
                    <div key={item.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-xl">
                      <div>
                        <span className="font-medium text-gray-800">{item[section.keyField]}</span>
                        {item.context && <span className="text-gray-400 text-xs ml-2">(when {item.context})</span>}
                        <p className="text-sm text-indigo-600 mt-0.5">→ "{item.intent}"</p>
                      </div>
                      <span className="bg-green-100 text-green-700 text-xs px-2 py-1 rounded-full font-medium">{item.count}x confirmed</span>
                    </div>
                  ))}
                </div>
              ) : <p className="text-gray-400 text-sm">No confirmed patterns yet</p>}
            </div>
          ))}
        </div>
      )}

      {activeTab === 'history' && (
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
          <div className="space-y-3">
            {history.map(h => (
              <div key={h.id} className="p-3 border border-gray-100 rounded-xl">
                <div className="flex items-start justify-between">
                  <div>
                    <p className="font-medium text-gray-800 text-sm">{h.confirmed_intent || h.predicted_intent}</p>
                    {h.explanation && <p className="text-xs text-gray-400 mt-0.5 italic">"{h.explanation}"</p>}
                    <div className="flex gap-2 mt-1">
                      {h.gesture && <span className="bg-purple-50 text-purple-600 text-xs px-2 py-0.5 rounded">👋 {h.gesture}</span>}
                      {h.sound && <span className="bg-green-50 text-green-600 text-xs px-2 py-0.5 rounded">🔊 {h.sound}</span>}
                      {h.object && <span className="bg-amber-50 text-amber-600 text-xs px-2 py-0.5 rounded">📍 {h.object}</span>}
                      {h.card && <span className="bg-blue-50 text-blue-600 text-xs px-2 py-0.5 rounded">🃏 {h.card}</span>}
                    </div>
                  </div>
                  <div className="text-right ml-3">
                    <span className={`text-xs px-2 py-1 rounded-full ${h.confidence >= 70 ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>{h.confidence}%</span>
                    <p className="text-xs text-gray-400 mt-1">{h.time}</p>
                    {h.caregiver_confirmed && <p className="text-xs text-green-600">✓ confirmed</p>}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {activeTab === 'notes' && (
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
          <h3 className="font-semibold text-gray-800 mb-4">Add Professional Note</h3>
          <textarea value={note} onChange={e => setNote(e.target.value)}
            className="w-full border border-gray-200 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-indigo-500 outline-none resize-none"
            rows={4} placeholder="Add clinical observations, goals, or progress notes. These will be used by AI to improve intent predictions..." />
          {savedMsg && <p className="text-green-600 text-sm mt-2">{savedMsg}</p>}
          <button onClick={saveNote} disabled={saving || !note.trim()}
            className="mt-3 bg-indigo-600 text-white px-6 py-2 rounded-xl text-sm font-medium hover:bg-indigo-700 disabled:opacity-60">
            {saving ? 'Saving...' : 'Save Note'}
          </button>
        </div>
      )}
    </div>
  )
}
